services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    # For raspi4
    #platform: linux/arm64/v8
    restart: unless-stopped
    #ports:
    #  - 8123:8123
    #privileged: true
    network_mode: host
    extra_hosts:
      - mosquitto:127.0.0.1
    #dns:
    #  - 8.8.8.8
    #  - 4.4.4.4
    volumes:
      - ./config:/config
      - /etc/localtime:/etc/localtime:ro
    #  - /run/dbus:/run/dbus:ro
    depends_on:
      - mosquitto

  mosquitto:
    #user: 999:994
    container_name: mosquitto
    image: eclipse-mosquitto
    # For raspi4
    #platform: linux/arm64/v8
    restart: unless-stopped
    network_mode: host
    #ports:
    #  - 1883:1883
    #  - 9001:9001 
    #environment:
    #  - TZ=Europe/Brussels
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    stdin_open: true
    tty: true

