version: '3'
services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    restart: unless-stopped
    ports:
      - 8123:8123
    volumes:
      - ./config:/config
      - /etc/localtime:/etc/localtime:ro
    #  - /run/dbus:/run/dbus:ro
    #privileged: true
    #network_mode: host
    #extra_hosts:
    #  - mosquitto:127.0.0.1
    depends_on:
      - mosquitto

  mosquitto:
    #user: 999:994
    container_name: mosquitto
    image: eclipse-mosquitto
    restart: unless-stopped
    ports:
      - 1883:1883
    #  - 9001:9001 
    #environment:
    #  - TZ=Europe/Brussels
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    stdin_open: true
    tty: true

  # mqtt-io:
  #   container_name: mqtt-io
  #   image: "ghcr.io/kevinvincent/mqtt-io:latest"
  #   restart: unless-stopped
  #   environment:
  #     - MQTT_BROKER=mosquitto
  #     - MQTT_PORT=1883
  #     - MQTT_USERNAME=homeassistant
  #     - MQTT_PASSWORD=homeassistant
  #     - MQTT_TOPIC_PREFIX=homeassistant
  #     - MQTT_DISCOVERY_PREFIX=homeassistant
  #     - MQTT_DISCOVERY_INTERVAL=60
  #     - MQTT_DISCOVERY_RETAIN=true



  # tapo