- id: '1713630315303'
  alias: Farm Low Flow
  description: Farm Low Flow
  trigger:
  - platform: numeric_state
    entity_id:
    - sensor.farm_flow
    below: 0.1
  condition: []
  action:
  - service: notify.farm_urban
    data:
      message: 'Warning! Farm Flow is running low.

        Check the sump or online at: https://farm.farmurban.co.uk/

        '
  mode: single
- id: '1713640115127'
  alias: Edible Wall Low Flow
  description: Edible Wall Low Flow
  trigger:
  - platform: numeric_state
    entity_id:
    - sensor.ew1_flow
    below: 0.1
  condition: []
  action:
  - service: notify.farm_urban
    data:
      message: 'Warning! Edible Wall Sump flow is running low.

        Check the sump or online at: https://farm.farmurban.co.uk/

        '
  mode: single
- id: '1713718060630'
  alias: Farm Lights On
  description: ''
  triggers:
  - at: '16:00:00'
    trigger: time
  conditions: []
  actions:
  - metadata: {}
    data: {}
    action: switch.turn_on
    target:
      entity_id: switch.all_farm_lights
  mode: single
- id: '1713718117980'
  alias: Farm Lights Off
  description: ''
  triggers:
  - at: '10:00:00'
    trigger: time
  conditions: []
  actions:
  - metadata: {}
    data: {}
    action: switch.turn_off
    target:
      entity_id: switch.all_farm_lights
  mode: single
