
# Loads default set of integrations. Do not remove.
default_config:

## Load frontend themes from the themes folder
#frontend:
#  themes: !include_dir_merge_named themes
#
automation: !include automations.yaml
#script: !include scripts.yaml
#scene: !include scenes.yaml

#template:
#  - sensor:
#      name: Industrial Fan
#tasmota_E0B226
#      state_topic: "tele/sonoffpow/SENSOR"
#      value_template: "{{value_json['ENERGY'].Power }}"
#      qos: 1
#      json_attributes_topic: "tele/sonoffpow/SENSOR"
#      json_attributes_template: "{{ value_json['ENERGY'] | tojson }}"

#jmht
switch:
  - platform: group
    unique_id: zipfarm_lights
    name: zipfarm lights
    entities:
      - switch.tasmota_2 #SONOFF1
      - switch.tasmota_3 #SONOFF3
      - switch.sonoff4 #SONOFF4

mqtt: !include mqtt.yaml