- sensor:
    unique_id: farm_temp
    name: "Farm Temp"
    state_topic: "sensors/stream/rpiarduino"
    device_class: "temperature"
    expire_after: 120
    value_template: >-
      {% from 'mqtt_parser.jinja' import parse_stream %}
      {{ parse_stream(value,'tempair') }}

- sensor:
    unique_id: farm_humidity
    name: "Farm Humidity"
    state_topic: "sensors/stream/rpiarduino"
    device_class: "humidity"
    expire_after: 120
    value_template: >-
      {% from 'mqtt_parser.jinja' import parse_stream %}
      {{ parse_stream(value,'humidity') }}

- sensor:
    unique_id: farm_light
    name: "Farm Light"
    state_topic: "sensors/stream/rpiarduino"
    device_class: "illuminance"
    expire_after: 120
    value_template: >-
      {% from 'mqtt_parser.jinja' import parse_stream %}
      {{ parse_stream(value,'light') }}

- sensor:
    unique_id: farm_co2
    name: "Farm CO2"
    state_topic: "sensors/stream/rpiarduino"
    device_class: "carbon_dioxide"
    expire_after: 120
    value_template: >-
      {% from 'mqtt_parser.jinja' import parse_stream %}
      {{ parse_stream(value,'co2') }}

- sensor:
    unique_id: farm_flow
    name: "Sump flow rate"
    state_topic: "sensors/stream/rpiarduino"
    device_class: "volume_flow_rate"
    expire_after: 120
    value_template: >-
      {% from 'mqtt_parser.jinja' import parse_stream %}
      {{ parse_stream(value,'flow') }}
